environments:
  default:
    values:
      - aissembleVersion: 1.13.0-SNAPSHOT
      - helm:
          valueFiles:
            - values.yaml
            - values-dev.yaml
          s3local:
            enabled: true
  ci:
    values:
      - aissembleVersion: 1.13.0-SNAPSHOT
      - helm:
          valueFiles:
            - values.yaml
            - values-ci.yaml
          s3local:
            enabled: false
    kubeContext: PLACEHOLDER-kubernetes-ci-context