{{- if not .Values.s3LocalEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: test-679-v1
  name: remote-auth-config
stringData:
  YOUR_ACCESS_KEY: YOUR_ACCESS_KEY
  YOUR_SECRET_KEY: YOUR_SECRET_VALUE
{{- end -}}